using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MySql.Data.MySqlClient;
using System.Windows.Forms;
using MySql.Data;

namespace StudentManagementSystem
{
    class MyStudentScore
    {  
        public static int ID = 0;
        public static int GetID
        {
            get { return ID; }
            set { ID = value; }
        }
        public static void LoadStudent(int ID)
        {
        }
        public static void Edit(int ID)
        {

        }
        public static void Delete(int ID)
        {

        }
        public static void Setting(int ID)
        {

        }
    }
}
